

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TABProject
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TABContext : DbContext
{
    public TABContext()
        : base("name=TABContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<app_user> app_user { get; set; }

    public virtual DbSet<client> clients { get; set; }

    public virtual DbSet<issue> issues { get; set; }

    public virtual DbSet<request> requests { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<system> systems { get; set; }

    public virtual DbSet<version> versions { get; set; }

    public virtual DbSet<worker_task> worker_task { get; set; }

}

}

