
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TABProject
{

using System;
    using System.Collections.Generic;
    
public partial class request
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public request()
    {

        this.issues = new HashSet<issue>();

    }


    public decimal id_request { get; set; }

    public decimal id_account_manager { get; set; }

    public decimal id_version { get; set; }

    public System.DateTime dt_open { get; set; }

    public string status { get; set; }

    public string description { get; set; }

    public string result { get; set; }

    public Nullable<System.DateTime> dt_final_cancel { get; set; }



    public virtual app_user app_user { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<issue> issues { get; set; }

    public virtual version version { get; set; }

}

}
