
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TABProject
{

using System;
    using System.Collections.Generic;
    
public partial class system
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public system()
    {

        this.versions = new HashSet<version>();

    }


    public decimal id_system { get; set; }

    public Nullable<decimal> id_related_system { get; set; }

    public decimal id_client { get; set; }

    public string type { get; set; }

    public string name { get; set; }



    public virtual client client { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<version> versions { get; set; }

}

}
