
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TABProject
{

using System;
    using System.Collections.Generic;
    
public partial class worker_task
{

    public decimal id_worker_task { get; set; }

    public string status { get; set; }

    public Nullable<decimal> id_worker { get; set; }

    public string result { get; set; }

    public string description { get; set; }

    public System.DateTime dt_open { get; set; }

    public decimal id_issue { get; set; }

    public Nullable<System.DateTime> dt_final_cancel { get; set; }



    public virtual app_user app_user { get; set; }

    public virtual issue issue { get; set; }

}

}
